development:
  host : "localhost"
  adapter: postgresql
  database: tvgl_dev
  username: futbolpal
  password: password
  pool: 5
  timeout: 5000 

test:
  host : "localhost"
  adapter: postgresql
  database: tvgl_test
  username: futbolpal
  password: password
  pool: 5
  timeout: 5000 

production:
  host : "localhost"
  adapter: postgresql
  database: tvgl
  username: futbolpal
  password: password
  pool: 5
  timeout: 5000 
